//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSEPM.Resources.Views.ManageAccount {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ManageAccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageAccountResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KSEPM.Resources.Views.ManageAccount.ManageAccountResource", typeof(ManageAccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string V_MA_form_newpassword {
            get {
                return ResourceManager.GetString("V_MA_form_newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль.
        /// </summary>
        public static string V_MA_form_oldpassword {
            get {
                return ResourceManager.GetString("V_MA_form_oldpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите новый пароль.
        /// </summary>
        public static string V_MA_form_repeatnewpassword {
            get {
                return ResourceManager.GetString("V_MA_form_repeatnewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string V_MA_form_submitchanges_btn {
            get {
                return ResourceManager.GetString("V_MA_form_submitchanges_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование пароля.
        /// </summary>
        public static string V_MA_main_title {
            get {
                return ResourceManager.GetString("V_MA_main_title", resourceCulture);
            }
        }
    }
}
