// <auto-generated />
namespace KSEPM.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class pointtype2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pointtype2));
        
        string IMigrationMetadata.Id
        {
            get { return "201410020719358_pointtype2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
