//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSEPM.Resources.Views.Sells {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SellResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SellResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KSEPM.Resources.Views.Sells.SellResource", typeof(SellResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продажи кресел за сегодня.
        /// </summary>
        public static string V_S_addedchairs_table_title {
            get {
                return ResourceManager.GetString("V_S_addedchairs_table_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string V_S_delete_btn {
            get {
                return ResourceManager.GetString("V_S_delete_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Править.
        /// </summary>
        public static string V_S_edit_btn {
            get {
                return ResourceManager.GetString("V_S_edit_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кресло.
        /// </summary>
        public static string V_S_form_chair {
            get {
                return ResourceManager.GetString("V_S_form_chair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите кресло.
        /// </summary>
        public static string V_S_form_chair_placeholder {
            get {
                return ResourceManager.GetString("V_S_form_chair_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка продажи.
        /// </summary>
        public static string V_S_form_sell_point {
            get {
                return ResourceManager.GetString("V_S_form_sell_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время продажи.
        /// </summary>
        public static string V_S_form_sell_time {
            get {
                return ResourceManager.GetString("V_S_form_sell_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продавец.
        /// </summary>
        public static string V_S_form_seller {
            get {
                return ResourceManager.GetString("V_S_form_seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список пуст, добавте сотрудников.
        /// </summary>
        public static string V_S_form_seller_emptylist_placeholder {
            get {
                return ResourceManager.GetString("V_S_form_seller_emptylist_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите продавца.
        /// </summary>
        public static string V_S_form_seller_placeholder {
            get {
                return ResourceManager.GetString("V_S_form_seller_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите место продажи.
        /// </summary>
        public static string V_S_form_sellpoint_placeholder {
            get {
                return ResourceManager.GetString("V_S_form_sellpoint_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выбора даты нажмите на календарь.
        /// </summary>
        public static string V_S_form_selltime_placeholder {
            get {
                return ResourceManager.GetString("V_S_form_selltime_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string V_S_form_submit_btn {
            get {
                return ResourceManager.GetString("V_S_form_submit_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить записи о продаже в базу данных.
        /// </summary>
        public static string V_S_main_subtitle {
            get {
                return ResourceManager.GetString("V_S_main_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новую запись о продаже.
        /// </summary>
        public static string V_S_main_title {
            get {
                return ResourceManager.GetString("V_S_main_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достижения.
        /// </summary>
        public static string V_S_table_td_achievement {
            get {
                return ResourceManager.GetString("V_S_table_td_achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string V_S_table_td_ammount {
            get {
                return ResourceManager.GetString("V_S_table_td_ammount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кресло.
        /// </summary>
        public static string V_S_table_td_chair {
            get {
                return ResourceManager.GetString("V_S_table_td_chair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string V_S_table_td_delete_btn {
            get {
                return ResourceManager.GetString("V_S_table_td_delete_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Править.
        /// </summary>
        public static string V_S_table_td_edit_btn {
            get {
                return ResourceManager.GetString("V_S_table_td_edit_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string V_S_table_td_name {
            get {
                return ResourceManager.GetString("V_S_table_td_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опции.
        /// </summary>
        public static string V_S_table_td_options {
            get {
                return ResourceManager.GetString("V_S_table_td_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очки.
        /// </summary>
        public static string V_S_table_td_points {
            get {
                return ResourceManager.GetString("V_S_table_td_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время продажи.
        /// </summary>
        public static string V_S_table_td_sell_date {
            get {
                return ResourceManager.GetString("V_S_table_td_sell_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка продажи.
        /// </summary>
        public static string V_S_table_td_sell_point {
            get {
                return ResourceManager.GetString("V_S_table_td_sell_point", resourceCulture);
            }
        }
    }
}
