//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSEPM.Resources.DisplayNames {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KSEPM.Resources.DisplayNames.DisplayName", typeof(DisplayName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string DN_Ammount {
            get {
                return ResourceManager.GetString("DN_Ammount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апрель.
        /// </summary>
        public static string DN_april {
            get {
                return ResourceManager.GetString("DN_april", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Август.
        /// </summary>
        public static string DN_august {
            get {
                return ResourceManager.GetString("DN_august", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кресло.
        /// </summary>
        public static string DN_chair {
            get {
                return ResourceManager.GetString("DN_chair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string DN_count {
            get {
                return ResourceManager.GetString("DN_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аракс.
        /// </summary>
        public static string DN_CVM_Arax {
            get {
                return ResourceManager.GetString("DN_CVM_Arax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крестовина.
        /// </summary>
        public static string DN_CVM_Cross {
            get {
                return ResourceManager.GetString("DN_CVM_Cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хромированная .
        /// </summary>
        public static string DN_CVM_Cross_chrome_coated {
            get {
                return ResourceManager.GetString("DN_CVM_Cross_chrome_coated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полиамидная.
        /// </summary>
        public static string DN_CVM_Cross_polyamide {
            get {
                return ResourceManager.GetString("DN_CVM_Cross_polyamide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Натуральное дерево.
        /// </summary>
        public static string DN_CVM_Cross_wooden {
            get {
                return ResourceManager.GetString("DN_CVM_Cross_wooden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дарынок.
        /// </summary>
        public static string DN_CVM_Darinok {
            get {
                return ResourceManager.GetString("DN_CVM_Darinok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дом мебели.
        /// </summary>
        public static string DN_CVM_Dom_Mebeli {
            get {
                return ResourceManager.GetString("DN_CVM_Dom_Mebeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дрим таун.
        /// </summary>
        public static string DN_CVM_Dream_Town {
            get {
                return ResourceManager.GetString("DN_CVM_Dream_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форум.
        /// </summary>
        public static string DN_CVM_Forum {
            get {
                return ResourceManager.GetString("DN_CVM_Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подголовник.
        /// </summary>
        public static string DN_CVM_HeadRest {
            get {
                return ResourceManager.GetString("DN_CVM_HeadRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регулировка угла наклона.
        /// </summary>
        public static string DN_CVM_Headrest_angle {
            get {
                return ResourceManager.GetString("DN_CVM_Headrest_angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ругулировка угла наклона и высоты.
        /// </summary>
        public static string DN_CVM_Headrest_angle_height {
            get {
                return ResourceManager.GetString("DN_CVM_Headrest_angle_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Механизмы.
        /// </summary>
        public static string DN_CVM_Mechanism {
            get {
                return ResourceManager.GetString("DN_CVM_Mechanism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовый.
        /// </summary>
        public static string DN_CVM_Mechanism_basic {
            get {
                return ResourceManager.GetString("DN_CVM_Mechanism_basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опора для ног - ring base.
        /// </summary>
        public static string DN_CVM_Mechanism_ring_base {
            get {
                return ResourceManager.GetString("DN_CVM_Mechanism_ring_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi synchro со слайдером.
        /// </summary>
        public static string DN_CVM_Mechanism_slander {
            get {
                return ResourceManager.GetString("DN_CVM_Mechanism_slander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп-опора.
        /// </summary>
        public static string DN_CVM_Mechanism_stop_support {
            get {
                return ResourceManager.GetString("DN_CVM_Mechanism_stop_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отделка.
        /// </summary>
        public static string DN_CVM_Onvay {
            get {
                return ResourceManager.GetString("DN_CVM_Onvay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нанесение логотипов.
        /// </summary>
        public static string DN_CVM_Onvay_logo {
            get {
                return ResourceManager.GetString("DN_CVM_Onvay_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дизайнерский шов - aristo.
        /// </summary>
        public static string DN_CVM_Onvay_stitch_aristo {
            get {
                return ResourceManager.GetString("DN_CVM_Onvay_stitch_aristo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дизайнерский шов - design.
        /// </summary>
        public static string DN_CVM_Onvay_stitch_design {
            get {
                return ResourceManager.GetString("DN_CVM_Onvay_stitch_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дизайнерский шов - fashion.
        /// </summary>
        public static string DN_CVM_Onvay_stitch_fashion {
            get {
                return ResourceManager.GetString("DN_CVM_Onvay_stitch_fashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дизайнерский шов - quatro.
        /// </summary>
        public static string DN_CVM_Onvay_stitch_quatro {
            get {
                return ResourceManager.GetString("DN_CVM_Onvay_stitch_quatro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дизайнерский шов - zeta.
        /// </summary>
        public static string DN_CVM_Onvay_stitch_zeta {
            get {
                return ResourceManager.GetString("DN_CVM_Onvay_stitch_zeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кристалы от swarovski.
        /// </summary>
        public static string DN_CVM_Onvay_swarovski {
            get {
                return ResourceManager.GetString("DN_CVM_Onvay_swarovski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шестой элемент.
        /// </summary>
        public static string DN_CVM_Six_element {
            get {
                return ResourceManager.GetString("DN_CVM_Six_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Три слона.
        /// </summary>
        public static string DN_CVM_Three_slona {
            get {
                return ResourceManager.GetString("DN_CVM_Three_slona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обивка.
        /// </summary>
        public static string DN_CVM_Upholstery {
            get {
                return ResourceManager.GetString("DN_CVM_Upholstery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экокожа/Антара.
        /// </summary>
        public static string DN_CVM_Upholstery_eco_leather {
            get {
                return ResourceManager.GetString("DN_CVM_Upholstery_eco_leather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кожа.
        /// </summary>
        public static string DN_CVM_Upholstery_leather {
            get {
                return ResourceManager.GetString("DN_CVM_Upholstery_leather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перфорированная экокожа.
        /// </summary>
        public static string DN_CVM_Upholstery_perforated_eco_leather {
            get {
                return ResourceManager.GetString("DN_CVM_Upholstery_perforated_eco_leather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш дом.
        /// </summary>
        public static string DN_CVM_Vash_dom {
            get {
                return ResourceManager.GetString("DN_CVM_Vash_dom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декабрь.
        /// </summary>
        public static string DN_december {
            get {
                return ResourceManager.GetString("DN_december", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта.
        /// </summary>
        public static string DN_email {
            get {
                return ResourceManager.GetString("DN_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Февраль.
        /// </summary>
        public static string DN_february {
            get {
                return ResourceManager.GetString("DN_february", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Январь.
        /// </summary>
        public static string DN_january {
            get {
                return ResourceManager.GetString("DN_january", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Июль.
        /// </summary>
        public static string DN_july {
            get {
                return ResourceManager.GetString("DN_july", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Июнь.
        /// </summary>
        public static string DN_june {
            get {
                return ResourceManager.GetString("DN_june", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Март.
        /// </summary>
        public static string DN_march {
            get {
                return ResourceManager.GetString("DN_march", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Май.
        /// </summary>
        public static string DN_may {
            get {
                return ResourceManager.GetString("DN_may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ноябрь.
        /// </summary>
        public static string DN_november {
            get {
                return ResourceManager.GetString("DN_november", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Октябрь.
        /// </summary>
        public static string DN_october {
            get {
                return ResourceManager.GetString("DN_october", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string DN_password {
            get {
                return ResourceManager.GetString("DN_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ.
        /// </summary>
        public static string DN_role {
            get {
                return ResourceManager.GetString("DN_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string DN_RVM_description {
            get {
                return ResourceManager.GetString("DN_RVM_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string DN_RVM_firstname {
            get {
                return ResourceManager.GetString("DN_RVM_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Офис.
        /// </summary>
        public static string DN_RVM_Office {
            get {
                return ResourceManager.GetString("DN_RVM_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На точке.
        /// </summary>
        public static string DN_RVM_Outside {
            get {
                return ResourceManager.GetString("DN_RVM_Outside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип продаж.
        /// </summary>
        public static string DN_RVM_pointtype {
            get {
                return ResourceManager.GetString("DN_RVM_pointtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string DN_RVM_secondname {
            get {
                return ResourceManager.GetString("DN_RVM_secondname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зачислен в штат.
        /// </summary>
        public static string DN_RVM_starttowork {
            get {
                return ResourceManager.GetString("DN_RVM_starttowork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Харьков.
        /// </summary>
        public static string DN_SDTVM_Kharkiv {
            get {
                return ResourceManager.GetString("DN_SDTVM_Kharkiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Киев.
        /// </summary>
        public static string DN_SDTVM_Kiev {
            get {
                return ResourceManager.GetString("DN_SDTVM_Kiev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Львов.
        /// </summary>
        public static string DN_SDTVM_Lvov {
            get {
                return ResourceManager.GetString("DN_SDTVM_Lvov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одесса.
        /// </summary>
        public static string DN_SDTVM_Odessa {
            get {
                return ResourceManager.GetString("DN_SDTVM_Odessa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сентябрь.
        /// </summary>
        public static string DN_september {
            get {
                return ResourceManager.GetString("DN_september", resourceCulture);
            }
        }
    }
}
