//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSEPM.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLayout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLayout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KSEPM.Resources.Views.Shared.MainLayout", typeof(MainLayout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветствую.
        /// </summary>
        public static string V_greetings {
            get {
                return ResourceManager.GetString("V_greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string V_language {
            get {
                return ResourceManager.GetString("V_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык.
        /// </summary>
        public static string V_language_choosetitle {
            get {
                return ResourceManager.GetString("V_language_choosetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string V_menu_about {
            get {
                return ResourceManager.GetString("V_menu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить продажу.
        /// </summary>
        public static string V_menu_add_sell {
            get {
                return ResourceManager.GetString("V_menu_add_sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить сотрудника.
        /// </summary>
        public static string V_menu_add_user {
            get {
                return ResourceManager.GetString("V_menu_add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудники.
        /// </summary>
        public static string V_menu_employees {
            get {
                return ResourceManager.GetString("V_menu_employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string V_menu_home {
            get {
                return ResourceManager.GetString("V_menu_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Линейные графики.
        /// </summary>
        public static string V_menu_linear_charts {
            get {
                return ResourceManager.GetString("V_menu_linear_charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Олимп.
        /// </summary>
        public static string V_menu_olympus {
            get {
                return ResourceManager.GetString("V_menu_olympus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Круговые графики.
        /// </summary>
        public static string V_menu_pie_charts {
            get {
                return ResourceManager.GetString("V_menu_pie_charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планы.
        /// </summary>
        public static string V_menu_plans {
            get {
                return ResourceManager.GetString("V_menu_plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблицы.
        /// </summary>
        public static string V_menu_tables {
            get {
                return ResourceManager.GetString("V_menu_tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки аккаунта.
        /// </summary>
        public static string V_settingsdropdown_accountsettings_title {
            get {
                return ResourceManager.GetString("V_settingsdropdown_accountsettings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие настройки.
        /// </summary>
        public static string V_settingsdropdown_anothersettings_title {
            get {
                return ResourceManager.GetString("V_settingsdropdown_anothersettings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string V_settingsdropdown_changepass_link {
            get {
                return ResourceManager.GetString("V_settingsdropdown_changepass_link", resourceCulture);
            }
        }
    }
}
