//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSEPM.Resources.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KSEPM.Resources.Errors.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кресло не выбрано.
        /// </summary>
        public static string ERR_addsellform_empty_chairselect {
            get {
                return ResourceManager.GetString("ERR_addsellform_empty_chairselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продавец не выбран.
        /// </summary>
        public static string ERR_addsellform_empty_sellerselect {
            get {
                return ResourceManager.GetString("ERR_addsellform_empty_sellerselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка продажи не выбрана.
        /// </summary>
        public static string ERR_addsellform_empty_sellpointselect {
            get {
                return ResourceManager.GetString("ERR_addsellform_empty_sellpointselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат почты введен не верно.
        /// </summary>
        public static string ERR_field_email_wrongformat {
            get {
                return ResourceManager.GetString("ERR_field_email_wrongformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; должно быть заполнено.
        /// </summary>
        public static string ERR_field_empty {
            get {
                return ResourceManager.GetString("ERR_field_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; должно быть заполнено.
        /// </summary>
        public static string ERR_field_empty_js {
            get {
                return ResourceManager.GetString("ERR_field_empty_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string ERR_field_notequalpasswords_js {
            get {
                return ResourceManager.GetString("ERR_field_notequalpasswords_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина поля &apos;{0}&apos; должно быть от {2} до {1} символов.
        /// </summary>
        public static string ERR_field_shortlong {
            get {
                return ResourceManager.GetString("ERR_field_shortlong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина поля  должна быть от {0} до {1} символов.
        /// </summary>
        public static string ERR_field_shortlong_js {
            get {
                return ResourceManager.GetString("ERR_field_shortlong_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страрый пароль не верен.
        /// </summary>
        public static string ERR_invalid_oldpassword {
            get {
                return ResourceManager.GetString("ERR_invalid_oldpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле почта или пароль пустое.
        /// </summary>
        public static string ERR_loginform_emply_passorlogin {
            get {
                return ResourceManager.GetString("ERR_loginform_emply_passorlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта или пароль неверны.
        /// </summary>
        public static string ERR_loginform_wrong_passorlogin {
            get {
                return ResourceManager.GetString("ERR_loginform_wrong_passorlogin", resourceCulture);
            }
        }
    }
}
