//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSEPM.Resources.Views.Charts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChartsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChartsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KSEPM.Resources.Views.Charts.ChartsResource", typeof(ChartsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Графичесое отображение эффективности продавцов и.т.д.
        /// </summary>
        public static string V_LC_main_subtitle {
            get {
                return ResourceManager.GetString("V_LC_main_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Линейные графики.
        /// </summary>
        public static string V_LC_main_title {
            get {
                return ResourceManager.GetString("V_LC_main_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Круговые графики отображения эффективности продавцов.
        /// </summary>
        public static string V_PC_main_subtitle {
            get {
                return ResourceManager.GetString("V_PC_main_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Круговые графики.
        /// </summary>
        public static string V_PC_main_title {
            get {
                return ResourceManager.GetString("V_PC_main_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показываются основные показатели ввиде стандартных таблиц.
        /// </summary>
        public static string V_TC_main_subtitle {
            get {
                return ResourceManager.GetString("V_TC_main_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовые таблицы эффективности.
        /// </summary>
        public static string V_TC_main_title {
            get {
                return ResourceManager.GetString("V_TC_main_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг продавцов.
        /// </summary>
        public static string V_TC_overall_table_title {
            get {
                return ResourceManager.GetString("V_TC_overall_table_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список кресел.
        /// </summary>
        public static string V_TC_sellpointranks_table_chairlist {
            get {
                return ResourceManager.GetString("V_TC_sellpointranks_table_chairlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка.
        /// </summary>
        public static string V_TC_sellpointranks_table_pointname {
            get {
                return ResourceManager.GetString("V_TC_sellpointranks_table_pointname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводная детальная таблица.
        /// </summary>
        public static string V_TC_sum_detailtable_title {
            get {
                return ResourceManager.GetString("V_TC_sum_detailtable_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достижения.
        /// </summary>
        public static string V_TC_table_td_achievement {
            get {
                return ResourceManager.GetString("V_TC_table_td_achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string V_TC_table_td_ammount {
            get {
                return ResourceManager.GetString("V_TC_table_td_ammount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во прод. кресел.
        /// </summary>
        public static string V_TC_table_td_chaircount {
            get {
                return ResourceManager.GetString("V_TC_table_td_chaircount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string V_TC_table_td_city {
            get {
                return ResourceManager.GetString("V_TC_table_td_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string V_TC_table_td_name {
            get {
                return ResourceManager.GetString("V_TC_table_td_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очки.
        /// </summary>
        public static string V_TC_table_td_points {
            get {
                return ResourceManager.GetString("V_TC_table_td_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата продажи.
        /// </summary>
        public static string V_TC_table_td_sell_date {
            get {
                return ResourceManager.GetString("V_TC_table_td_sell_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка продажи.
        /// </summary>
        public static string V_TC_table_td_sell_point {
            get {
                return ResourceManager.GetString("V_TC_table_td_sell_point", resourceCulture);
            }
        }
    }
}
